spring:
  application:
    name: vehiculos
  
server:
  port: 0
    
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8075/eureka/      
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
      user.name: ${security.user.name}
      user.password: ${security.user.password}
 
security:
  user:
    name: user
    password: pass 

  basic:
    enabled: false
    
      
---

spring:
  profiles: docker
 
  data:
    mongodb:
      uri: mongodb://mongodb/microserviceblog

eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka-docker:8075/eureka/      
  instance:
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}  