spring:
  application:
    name: vehiculos
    
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:1111/eureka/      
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}  
      
---

spring:
  profiles: docker
 
  data:
    mongodb:
      uri: mongodb://mongodb/microserviceblog

eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka-docker:1111/eureka/      
  instance:
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}  